config/routes.rb
Heegel::Application.routes.draw do
  resources :blogs

  match '/about',   to: 'static_pages#about'
  match '/store',   to: 'store#index'
  match '/login',   to: 'sessions#new'
  match '/logout',  to: 'sessions#destroy'

  resources :sessions
  
  resources :products do
    collection { post :sort }
    resource :messages
  end

  root to: 'products#index', as: 'index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/message.rb
class Message
	include ActiveAttr::Model
  
	attribute :name
  attribute :email
  attribute :telefon
  attribute :address
  attribute :order

  attr_accessible :address, :email, :name, :order, :telefon

  validates :name, presence: :true
  validates :email, presence: :true
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_length_of :order, :maximum => 500
end

app/models/product.rb
class Product < ActiveRecord::Base
  before_save :set_position

  attr_accessible :amount, :creation_date_est, :creation_date_eng, 
  	:description_est, :description_eng, :measurement_est, :measurement_eng, 
  	:price, :image, :image_hover, :position, :title_est, :title_eng

  validates :title_eng, presence: :true, uniqueness: :true
  validates :title_est, presence: :true, uniqueness: :true
  validates :title_eng, presence: :true, uniqueness: :true
  validates :image, presence: :true, uniqueness: :true
  validates :price, numericality: :true

  mount_uploader :image, ImageUploader
  mount_uploader :image_hover, ImageHoverUploader

  protected

  def set_position
    self.position ||= 1 + (Product.where('id=?',id).maximum(:position) || 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :admin?

  protected

  def authorize
  	unless admin?
  		flash[:notice] = "Please log in"
  		redirect_to products_path
  		false
  	end
  end

  def admin?
  	session[:password] == ENV["ADMIN_PASS"]
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new(params[:message])
  end

  def create
    @message = Message.new(params[:message])
    if verify_recaptcha() and @message.valid?
      Order.notify(@message).deliver
      redirect_to products_path, notice: "Ait&auml;h tellimuse eest, v&otilde;tame 
      Sinuga peatselt &uuml;hendust!<br /> Thank you for your order, we'll get 
      back to you shortly.".html_safe
    else
      render "new"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authorize, except: :index

  def index
    @products = Product.order("position")

    respond_to do |format|
      format.html 
      format.json { render json: @products }
    end
  end

  def new
    @product = Product.new

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  #update order after sorting products
  def sort
  params[:product].each_with_index do |id, index|
    Product.update_all({position: index+1}, {id: id})
  end
  render nothing: true
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		session[:password] = params[:password]
		if admin?
			flash[:notice] = 'Logged in'
			redirect_to products_path
		else
			flash[:notice] = 'nope'
			redirect_to controller: :sessions, action: :new
		end
	end

	def destroy
		reset_session
		flash[:notice] = 'Logged out'
		redirect_to products_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
	def index
		@products = Product.all	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->

<head>
	<meta charset="utf-8">
	<meta name="description" content="">
	<meta name="author" content="whyservices">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Heegel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">

		<header class="eleven columns add-bottom">
			<div class="five columns alpha logo">
				<%= link_to(image_tag("heegel-header-est_288x100.png", 
					class: "remove-bottom", alt: "Käsitööklubi Hegel", title: "Käsitööklubi Hegel"), index_path) %>
				<br />
				<%= image_tag("header-line.png", class: "remove-bottom", alt: "Titel Underline", title: "Titel Underline") %>		
				<br />			
					<span class="eng">
						* untranslateable pun mixing sublime philosophy with mundane	manual skills
					</span>
					<span class="ee">&nbsp;<br />&nbsp;</span>
			</div>

			<nav class="six columns omega navigation">
				<%= link_to(image_tag("button-blog.png", mouseover: "button-blog_hover.png", width: "80", alt: "blog", title: "blog", class: "nav-link"), '') %>
				<%= link_to(image_tag("button-about.png", mouseover: "button-about_hover.png", width: "80", alt: "blog", title: "about", class: "nav-link"), about_path) %>
				<%= link_to(image_tag("button-shop.png", mouseover: "button-shop_hover.png", width: "80", alt: "shop", title: "shop", class: "nav-link"), store_path) %>
			</nav> 

		</header>
	
	<%= yield %>

	</div><!-- container -->
<%= debug(params) if Rails.env.development? %>
	<footer class="footer">
		&copy; heegel.ee<br />
		
		<%= link_to(image_tag("http://www.whyservices.eu/logo_whyservices_badge.png"), "http://www.whyservices.eu") %>

	</footer>


</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message, :url => product_messages_path) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="new-message-subset">
  <div class="field">
    <%= f.label :order, "Tellimus / Order" %>
    <%= f.text_area :order, value: params[:order], rows:5, columns:10 %>
  </div>
  <div class="field">
    <%= f.label :name, "Nimi / Name" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, "E-post / Email" %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefon, "Telefon / Phone" %>
    <%= f.text_field :telefon %>
  </div>
  <div class="field">
    <%= f.label :address, "Aadress (tänav, linn, riik)" %>
    <%= f.label :address, "Address (street, city, country)" %>
    <%= f.text_area :address, rows:5, columns:10 %>
  </div>
  <div>
  <%= recaptcha_tags theme: 'clean' %>
  </div>
  <div class="actions">
    <%= f.submit "Saada tellimus / Send order" %>
  </div>
</div>

<% end %>

app/views/messages/new.html.erb
<section class="eleven columns stitches content">
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>

	<h1>Order form / Tellimisvorm</h1>
	<p>Tellimiseks saada meile siit e-kiri oma sooviga.<br>
	(Kas lugesid infot tellimise kohta meie <%= link_to("poe lehelt", store_path) %>?) 
	</p>
	<p>In order to order, send us an e-mail via this form.<br>
	(Did you read the info about ordering in our <%= link_to("shop section", store_path) %>?) 
	</p>

	<%= render 'form' %>

</section>

app/views/order/notify.text.erb
Dear <%= @message.name %>  

Thank you for your order from heegel.ee.    

This is a copy of the order you sent us:
 
<%= @message.order %>

We will get in touch with you shortly.

Kind regards
the team of heegel.ee

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="new-product-subset">
  <div class="field">
    <%= f.label "English" %>
    <%= f.label :title_eng, "name of product" %>
    <%= f.text_field :title_eng %>
  </div>
  <div class="field">
    <%= f.label "eesti keeles" %>
    <%= f.label :title_est, "toote nimi" %>
    <%= f.text_field :title_est %>
  </div>
  <div class="field">
    <%= f.label :creation_date_eng, "time of creation" %>
    <%= f.label :creation_date_eng, "(i.e. January 2007)" %>
    <%= f.text_field :creation_date_eng %>
  </div>
  <div class="field">
    <%= f.label :creation_date_est, "valmistamise aeg" %>
    <%= f.label :creation_date_est, "(nt jaanuar 2007)" %>
    <%= f.text_field :creation_date_est %>
  </div>
  <div class="field">
    <%= f.label :measurement_eng, "measurements" %>
    <%= f.label :measurement_eng, "(i.e. 5.5 x 5 cm or Ø 80 cm)" %>
    <%= f.text_field :measurement_eng %>
  </div>
  <div class="field">
    <%= f.label :measurement_est, "mõõdud" %>
    <%= f.label :measurement_est, "(nt 5,5 x 5 cm või Ø 80 cm)" %>
    <%= f.text_field :measurement_est %>
  </div>
  <div class="field">
    <%= f.label :description_eng, "description" %>
    <%= f.text_area :description_eng, rows: "3" %>
  </div>
  <div class="field">
    <%= f.label :description_est, "kirjeldus" %>
    <%= f.text_area :description_est, rows: "3"  %>
  </div>
</div>

  <div class="field">
    <%= f.label :amount, "amount / kogus" %>
    <%= f.label :amount, "(kui komplektis on mitu asja, kirjuta siia number)" %>
    <%= f.text_field :amount, style: "width: 5em" %>


  <div class="field">
    <%= f.label :price, "price / hind" %>
    <%= f.text_field :price, style: "width: 5em" %>
  </div>

  <div class="field">
    <%= f.label :image, "image / pilt" %>
    <%= f.label :image, "(.png läbipaistval taustal)" %>
    <%= f.file_field :image %>
    <!-- todo image_cache, remove_image, image_hover_cache, remove_image_hover -->
  </div>
  <div class="field">
    <%= f.label :image_hover, "hover image / pildi efekt " %>
        <%= f.label :image_hover, "(.png läbipaistval taustal)" %>
    <%= f.file_field :image_hover %>
  </div>

  <div class="actions">
    <%= f.submit "add product / lisa toode" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<section class="eleven columns stitches content">
<p id="notice"><%= notice %></p>
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</section>

app/views/products/index.html.erb
<section class="eleven columns stitches content">
  <%= flash[:alert] %>

<p id="notice"><%= notice %></p>


  <% unless admin? %>

  <div class="row info">
    <%= image_tag("info-est.png", id: "info-img") %>    

    <div id="info-txt">
      <span class="ee">
        <strong>Iga ese on vestlus:</strong> 
          See, millest me r&auml;&auml;kisime, on kirjas v&auml;ikesel kaardikesel<br />
        <strong>Iga ese on s&uuml;ndmus:</strong> 
          Asjad s&uuml;nnivad siis, kui me kokku saame ja juttu r&auml;&auml;gime<br />
        <strong>Iga ese on kordumatu:</strong> 
          Taaskasutame aegade jooksul kogutud materjale
      </span>
      <span class="eng">
        <strong>Every item is a conversation:</strong> 
          What we talked about is written on a small card<br />
        <strong>Every item is an event:</strong> 
          Things are created when we get together on a cosy saturday morning<br />
        <strong>Every item is unique:</strong> 
          We recycle our collection of second-hand materials
      </span>
    </div>
    <span id="lang-switch">in English</span>
  </div>
  <% end %>

  <div class="examples ten columns">
    <% if admin? %>
    <div class="row sort">
      Sort items and add new:
      <ul id="products" data-update-url="<%= sort_products_url %>">
        <% @products.each do |product| %>
          <%= content_tag_for :li, product do %>
            <%= image_tag product.image.url(:thumb).to_s %>
          <% end %>
        <% end %>
      </ul>
      <br style="clear:left;" />
      <%= link_to 'add product / lisa toode', new_product_path %><br />
      <%= link_to 'logout', "/logout" %>
    </div>
    <% end %> 

    <% @products.each do |product| %>
    <div class="product-index-image">
      <% if product.image_hover.blank? %>
        <%= image_tag product.image.url(:column).to_s, 
          width: "280", id: "product-#{product.id}" %>
      <% else %>
        <%= image_tag product.image.url(:column).to_s, 
          mouseover: product.image_hover.url(:column).to_s,
          width: "280", id: "product-#{product.id}" %>
      <% end %>
      <br />
      <% if admin? %>
      <span class="edit">
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= link_to 'Delete', product, method: :delete, 
            data: { confirm: 'Are you sure?' } %>
      </span>
      <% end %>
    </div>
    <% end %>
    
  </div>
</section><!-- content -->

<aside class="five columns">
  <div class="section">

    <% @products.each do |product| %>
      <div class="infobox product-<%= product.id %>">
        <strong><%= product.title_est %> </strong><br />
        <%= product.measurement_est %><br />
        <%= product.creation_date_est %><br />
        <br />
        <%= product.description_est %><br />
        <br />
        Hind <%= product.price.to_i %> eur&nbsp;
          <% unless product.amount.blank? %>
            (<%= product.amount %> tk)
          <% end %>
        <%= link_to "Telli", new_product_messages_path(product, order: product.title_est) %>
        <br />
        <br />
        <br />
        <strong><%= product.title_eng %> </strong><br />
        <%= product.measurement_eng %><br />
        <%= product.creation_date_eng %><br />
        <br />
        <%= product.description_eng %><br />
        <br />
        Price <%= product.price.to_i %> eur&nbsp;
          <% unless product.amount.blank? %>
            (<%= product.amount %> pcs)
          <% end %>
        <%= link_to "Order", new_product_messages_path(product, order: product.title_eng) %>
      </div>
    <% end %>

  </div>
</aside>

app/views/products/new.html.erb
<section class="eleven columns stitches content">
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>
</section>

app/views/static_pages/about.html.erb
<section class="row sixteen columns about">
	<article class="row seven columns alpha" style="padding-top:10px;">
		Oleme &uuml;ks tavaline perekond, kes saab aeg-ajalt laup&auml;eva hommikuti &uuml;hes Mustam&auml;e p&auml;ikeselises korteris kokku. Et juttu r&auml;&auml;kida, filosofeerida, laulda, kiluv&otilde;ileibu s&uuml;&uuml;a ja kohvi juua. Selle saateks meeldib osavamatele meist teha k&auml;sit&ouml;&ouml;d: heegeldada, kududa, &otilde;mmelda. Teised, kelle loomingu jaoks on hoole ja armastusega meisterdatud eraldi kast kirjaga "kassi m&auml;nguasjad", kerivad jutul&otilde;nga ja painutavad teadmiste piire. Meile meeldib otsida vastuseid ja leida k&uuml;simusi. M&otilde;nikord teeme asju &uuml;ksteisele, kuid teinekord on t&ouml;&ouml;- ja jutuhoog nii suur, et asju saab rohkem, kui meil endal tarvis.<br />
		<br />
		<br />
		We are an ordinary family that meets every once in a while on a Saturday morning in a sunny apartment in Mustam&auml;e, Tallinn, Estonia. To have a chat, to be philosophical, to sing, to eat sprat sandwiches and drink coffee. The more skillful of us like to accompany that with a little bit of handicraft: crocheting, knitting, sewing. The others, for whose production we have lovingly made a box that says "the cat's toys" on it, work with words and stretch the boundaries of knowledge. We like to look for answers and find questions. Sometimes we make stuff for each other but at other times we end up with more things than we need.
	</article>

	<div class="row four columns trio-singles stitches">
		<%= image_tag("about_vanaema_170.png", class: "about-img", alt: "Vanaema", title: "Vanaema") %><br />
		<%= image_tag("about_tiina_150.png", class: "about-img", alt: "Tiina", title: "Tiina") %><br />
		<%= image_tag("about_kass_130.png", class: "about-img", alt: "Kass", title: "Kass") %>	
	</div>	

	<div class="row four columns trio-unit">
		<%= image_tag("about_trio.png", class: "about-img", alt: "Trio", title: "Trio") %>
	</div>

	<div class="row five columns omega">
		<%= image_tag("name-vanaema.png", class: "name-img", alt: "Vanaema", title: "Vanaema") %><br />
		<%= image_tag("name-tiina.png", class: "name-img", alt: "Tiina", title: "Tiina") %><br />
		<%= image_tag("name-kass.png", class: "name-img", alt: "Kass", title: "Kass") %>
	</div>		
</section><!-- content -->

app/views/store/_info.html.erb
<!-- <tr>
<td><%= #product.creation_eng %></td>
<td><%= #product.creation_ee %></td>
<td><%= #product.measurement_eng %></td>
<td><%= #product.measurement_ee %></td>
<td><%= #product.description_eng %></td>
<td><%= #product.description_ee %></td>
<td><%= #product.price %></td>
<td><%= #product.amount_eng %></td>
<td><%= #product.amount_ee %></td>
<td><%= #product.price_by_amount %></td>
</tr> -->

<table>
<tr>
<th>Creation eng</th>
<th>Creation ee</th>
<th>Measurement eng</th>
<th>Measurement ee</th>
<th>Description eng</th>
<th>Description ee</th>
<th>Price</th>
<th>Amount eng</th>
<th>Amount ee</th>
<th>Price by amount</th>
<th></th>
<th></th>
<th></th>
</tr>


</table>

<%= link_to 'Edit', edit_product_path(product) %>
<%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/store/index.html.erb
<section class="eleven columns stitches content">
<p id="notice"><%= notice %></p>
	<section class="ten columns add-bottom">
		<h1>Tellimine</h1>
		<p>
			Enamik kodulehel olevaid asju on ainueksemplarid ja leidnud juba uue omaniku. Saame Sulle valmistada samasuguse, kuigi v&otilde;ib juhtuda, et teist v&auml;rvi l&otilde;ngast v&otilde;i teise mustriga kangastest. Tellida saab kirja teel t&auml;ites tellimisvormi. Sinna saad kirjutada ka oma eelistused v&otilde;i erisoovid, k&uuml;sida meil lisainfot v&otilde;i lisapilte, uurida materjalide v&otilde;i t&ouml;&ouml; valmimise aja kohta. Tellimusvormi saadab arvuti meie meiliaadressidele ja edasi saame suhelda juba otse. Tasuda saab panga&uuml;lekandega. Valmis eseme paneme posti (eseme hinnale lisandub postitasu vastavalt <a href="http://www.post.ee/failid/UPT_kiri_km_ga_2012.pdf" target="_blank" title="Eesti Posti hinnakirjale">Eesti Posti hinnakirjale</a>).
		</p>
		<p>
		Juhul, kui saadame paki Eesti Posti t&auml;hitud maksikirjana, on riigisisesed hinnad j&auml;rgmised:
		</p>
		<p>
		kuni 250 g&nbsp;&nbsp;&nbsp;2.20 eur<br />
		kuni 500 g&nbsp;&nbsp;&nbsp;2.40 eur<br />
		kuni 1 kg&nbsp;&nbsp;&nbsp;2.70 eur<br />
		kuni 2 kg&nbsp;&nbsp;&nbsp;3.70 eur
		</p>

		<h1>Ordering</h1>
		<p>
		Most of the things on our web page are unique objects and are already at home with their new owners. We can make You a new one that looks the same, although it can happen that we use yarn of another colour or fabrics with different patterns.<br />
		To order, send us an e-mail via the link next to the object. That is also where You can mention Your preferences or special requests, ask for additional information or pictures, inquire about materials or how much time it will take. The computer will send the order form to our e-mail addresses and we can continue correspondence directly. You can pay via a bank transfer. We will post the order with Eesti Post according to their <a href="http://www.post.ee/failid/UPT_kiri_km_ga_2012.pdf" target="_blank" title="Eesti Post price list">price list</a>. The postage fee will be added to the price of the order.
		</p>
		<p>
		Postage fees are as follows:
		</p>
		<div style="float:left;padding-right:3em;">
		<strong>inside EU</strong><br />
		up to 250 g&nbsp;&nbsp;&nbsp;4.00 eur<br />
		up to 500 g&nbsp;&nbsp;&nbsp;6.00 eur<br />
		up to 1 kg&nbsp;&nbsp;&nbsp;10.00 eur<br />
		up to 2 kg&nbsp;&nbsp;&nbsp;14.00 eur
		</div>
		<div>
		<strong>outside EU</strong><br />
		up to 250 g&nbsp;&nbsp;&nbsp;4.50 eur<br />
		up to 500 g&nbsp;&nbsp;&nbsp;8.00 eur<br />
		up to 1 kg&nbsp;&nbsp;&nbsp;12.00 eur<br />
		up to 2 kg&nbsp;&nbsp;&nbsp;18.00 eur
		</div>
	</section>

	<section class="ten columns add-bottom">
		<h1>Product list</h1>
		<% @products.each do |product| %>
		<div class="store-index-item">
			<div class="store-index-image">
				<%= image_tag product.image.url(:thumb).to_s %>
			</div>
			<div class="store-index-text">
				<strong><%= product.title_est %> </strong><br />
		    <%= product.measurement_est %><br />
		    Hind <%= product.price.to_i %> eur 
		    <% unless product.amount.blank? %>
		      (<%= product.amount %> tk)
		    <% end %>
		    <%= link_to "Telli", new_product_messages_path(product, order: product.title_est) %><br />
		    <br />
		    <strong><%= product.title_eng %> </strong><br />
		    <%= product.measurement_eng %><br />
		    Price <%= product.price.to_i %> eur 
		    <% unless product.amount.blank? %>
		      (<%= product.amount %> pcs)
		    <% end %>
		    <%= link_to "Order", new_product_messages_path(product, order: product.title_eng) %>
			</div>
		</div>
		<% end %>
	</section>
</section>